package com.training.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Paper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("申請者名")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("申請書ID")
	private java.lang.Integer paperId;
	@org.kie.api.definition.type.Label("申請書タイプ")
	private java.lang.String paperType;
	@org.kie.api.definition.type.Label("申請日")
	private java.util.Date submitDate;

	@org.kie.api.definition.type.Label(value = "予算")
	private java.lang.Integer budget;

	public Paper() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getPaperId() {
		return this.paperId;
	}

	public void setPaperId(java.lang.Integer paperId) {
		this.paperId = paperId;
	}

	public java.lang.String getPaperType() {
		return this.paperType;
	}

	public void setPaperType(java.lang.String paperType) {
		this.paperType = paperType;
	}

	public java.util.Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(java.util.Date submitDate) {
		this.submitDate = submitDate;
	}

	public java.lang.Integer getBudget() {
		return this.budget;
	}

	public void setBudget(java.lang.Integer budget) {
		this.budget = budget;
	}

	public Paper(java.lang.String name, java.lang.Integer paperId,
			java.lang.String paperType, java.util.Date submitDate,
			java.lang.Integer budget) {
		this.name = name;
		this.paperId = paperId;
		this.paperType = paperType;
		this.submitDate = submitDate;
		this.budget = budget;
	}

}